import LoginPage from '@/components/Login/Login';
import { Metadata } from 'next';
import React from 'react';
export const metadata: Metadata = {
  title: "Login",
  description: "Generated by Login",
};
const Login = () => {
  return (
    <>
      <LoginPage/>
    </>
  );
};

export default Login;